name: Release
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v3

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 12.x

      - name: Run npm deploy:prod
        run: |
          npm ci
          npm run deploy:prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
